-- 
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 2026.1.77.0
-- Product Home Page: https://www.devart.com/dbforge/postgresql/studio
-- Script date 7/4/2026 5:18:48 PM
-- Source server version: 18.3
-- Source connection string: User Id=postgres_admin;Host=postgres.cpuicc6e4ab6.eu-north-1.rds.amazonaws.com;Port=5432;Database=postgres;Unicode=True;Connection Timeout=15;Integrated Security=False;SSLMode=Require;SSL TLS Protocol=1.2
-- Target server version: 18.3
-- Target connection string: User Id=postgres_admin;Host=postgres.cpuicc6e4ab6.eu-north-1.rds.amazonaws.com;Port=5432;Database=saas_prod;Unicode=True;Connection Timeout=15;Integrated Security=False;SSLMode=Require;SSL TLS Protocol=1.2
-- Run this script against saas_prod to synchronize it with saas_staging
-- 


--
-- Start Transaction
--
BEGIN;

--
-- Drop foreign key
--
ALTER TABLE public.payments 
   DROP CONSTRAINT payments_invoice_id_fkey;

--
-- Drop view "public"."tenant_revenue_summary"
--
DROP VIEW public.tenant_revenue_summary;

--
-- Drop foreign key
--
ALTER TABLE public.audit_log 
   DROP CONSTRAINT audit_log_user_id_fkey;

--
-- Drop foreign key
--
ALTER TABLE public.support_tickets 
   DROP CONSTRAINT support_tickets_user_id_fkey;

--
-- Drop foreign key
--
ALTER TABLE public.usage_events 
   DROP CONSTRAINT usage_events_user_id_fkey;

--
-- Drop foreign key
--
ALTER TABLE public.audit_log 
   DROP CONSTRAINT audit_log_tenant_id_fkey;

--
-- Drop foreign key
--
ALTER TABLE public.invoices 
   DROP CONSTRAINT invoices_tenant_id_fkey;

--
-- Drop foreign key
--
ALTER TABLE public.subscriptions 
   DROP CONSTRAINT subscriptions_tenant_id_fkey;

--
-- Drop foreign key
--
ALTER TABLE public.support_tickets 
   DROP CONSTRAINT support_tickets_tenant_id_fkey;

--
-- Drop foreign key
--
ALTER TABLE public.usage_events 
   DROP CONSTRAINT usage_events_tenant_id_fkey;

--
-- Drop foreign key
--
ALTER TABLE public.users 
   DROP CONSTRAINT users_tenant_id_fkey;

--
-- Create column "health_score" on table "public"."tenants"
--
ALTER TABLE public.tenants
  ADD health_score integer DEFAULT 100;

--
-- Create column "account_owner" on table "public"."tenants"
--
ALTER TABLE public.tenants
  ADD account_owner character varying(120);

--
-- Drop index "idx_users_tenant_id" from table "public"."users"
--
DROP INDEX public.idx_users_tenant_id;

--
-- Create foreign key
--
ALTER TABLE public.users 
  ADD FOREIGN KEY (tenant_id)
    REFERENCES public.tenants(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Drop index "idx_usage_events_tenant_id" from table "public"."usage_events"
--
DROP INDEX public.idx_usage_events_tenant_id;

--
-- Create index "idx_usage_events_tenant_created_at" on table "public"."usage_events"
--
CREATE INDEX idx_usage_events_tenant_created_at
  ON public.usage_events USING btree (tenant_id int4_ops, created_at timestamp_ops DESC);

--
-- Create foreign key
--
ALTER TABLE public.usage_events 
  ADD FOREIGN KEY (user_id)
    REFERENCES public.users(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE public.usage_events 
  ADD FOREIGN KEY (tenant_id)
    REFERENCES public.tenants(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE public.support_tickets 
  ADD FOREIGN KEY (tenant_id)
    REFERENCES public.tenants(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE public.support_tickets 
  ADD FOREIGN KEY (user_id)
    REFERENCES public.users(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Drop index "idx_subscriptions_tenant_id" from table "public"."subscriptions"
--
DROP INDEX public.idx_subscriptions_tenant_id;

--
-- Create foreign key
--
ALTER TABLE public.subscriptions 
  ADD FOREIGN KEY (tenant_id)
    REFERENCES public.tenants(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Drop index "idx_invoices_tenant_id" from table "public"."invoices"
--
DROP INDEX public.idx_invoices_tenant_id;

--
-- Create index "idx_invoices_tenant_status_due_date" on table "public"."invoices"
--
CREATE INDEX idx_invoices_tenant_status_due_date
  ON public.invoices USING btree (tenant_id int4_ops, status text_ops, due_date date_ops);

--
-- Create foreign key
--
ALTER TABLE public.invoices 
  ADD FOREIGN KEY (tenant_id)
    REFERENCES public.tenants(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE public.payments 
  ADD FOREIGN KEY (invoice_id)
    REFERENCES public.invoices(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create view "public"."tenant_revenue_summary"
--
CREATE VIEW public.tenant_revenue_summary
AS
	SELECT t.id AS tenant_id,
    t.company_name,
    t.industry,
    t.country,
    p.name AS plan_name,
    s.status AS subscription_status,
    sum(i.amount) FILTER (WHERE i.status::text = 'paid'::text) AS paid_revenue,
    sum(i.amount) FILTER (WHERE i.status::text = 'overdue'::text) AS overdue_revenue,
    count(i.id) AS invoice_count
   FROM tenants t
     JOIN subscriptions s ON s.tenant_id = t.id
     JOIN plans p ON p.id = s.plan_id
     LEFT JOIN invoices i ON i.tenant_id = t.id
  GROUP BY t.id, t.company_name, t.industry, t.country, p.name, s.status;

--
-- Drop index "idx_audit_log_tenant_id" from table "public"."audit_log"
--
DROP INDEX public.idx_audit_log_tenant_id;

--
-- Create index "idx_audit_log_risk_created_at" on table "public"."audit_log"
--
CREATE INDEX idx_audit_log_risk_created_at
  ON public.audit_log USING btree (risk_level text_ops, created_at timestamp_ops DESC);

--
-- Create foreign key
--
ALTER TABLE public.audit_log 
  ADD FOREIGN KEY (user_id)
    REFERENCES public.users(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE public.audit_log 
  ADD FOREIGN KEY (tenant_id)
    REFERENCES public.tenants(id)
      ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Commit Transaction
--
COMMIT;